### ISSUE TITLE
Card does not function correctly inside conditional card

### ISSUE THREAD

**Issue by J-Hurtta** [thomasloven/lovelace-gap-card#4]
I am currently using layout-card in a vertical mode in my Lovelace setup. I'm trying to use gap-cards to achieve badge-like functionality, as badges are not supported with `panel:true`. I am using three conditional cards, one for the timer card and two for gap-cards. In the following images, I have added entity cards with sensor.time to highlight the issue.

My YAML:
```
cards:
  - card:
      type: 'custom:gap-card'
      height: 94
    conditions:
      - entity: sensor.alexa_next_timer
        state_not: 'false'
    type: conditional
  - type: entity
    entity: sensor.time
  - break
  - card:
      entity: sensor.alexa_next_timer
      icon: '0'
      name: Next Alexa timer
      type: entity
    conditions:
      - entity: sensor.alexa_next_timer
        state_not: 'false'
    type: conditional
  - type: entity
    entity: sensor.time
  - break
  - card:
      type: 'custom:gap-card'
      height: 94
    conditions:
      - entity: sensor.alexa_next_timer
        state_not: 'false'
    type: conditional
  - type: entity
    entity: sensor.time
layout: vertical
type: 'custom:layout-card'
```

No timer active:
![image](https://user-images.githubusercontent.com/58122372/82120301-abfeb200-978d-11ea-9564-b3b839e4433a.png)

Timer active:
![image](https://user-images.githubusercontent.com/58122372/82120318-ca64ad80-978d-11ea-835e-2075581ff361.png)

How it should look (conditional cards replaced with gap-cards):
![image](https://user-images.githubusercontent.com/58122372/82120325-db152380-978d-11ea-9a1e-d0bcd50f26e8.png)
